import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from '@/components/layout/Header.jsx'

const openSans = Open_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "CDA Motos de la Sexta",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
